name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Clang
      run: sudo apt-get install -y clang

    - name: Install Xmake
      run: |
        curl -fsSL https://xmake.io/shget.text | bash
        echo 'export PATH=$HOME/.local/bin:$PATH' >> $GITHUB_ENV
        source $GITHUB_ENV
        ~/.xmake/bin/xmake --version

    - name: Configure xmake
      run: xmake f -c --toolchain=ZennityLang_Toolchain

    - name: Build project
      run: xmake

    - name: Run tests
      run: ./build/prompt
