name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang curl

    - name: Install Xmake
      run: |
        curl -fsSL https://xmake.io/shget.text | bash
        echo "$HOME/.xmake/bin" >> $GITHUB_PATH

    - name: Configure xmake
      run: xmake f -c --toolchain=ZennityLang_Toolchain

    - name: Build project
      run: xmake

    - name: Run tests
      run: ./build/prompt
